[package]
name = "minigene"
version = "0.1.0"
authors = ["Joël Lupien (Jojolepro) <jojolepro@jojolepro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = { path = "../bracket-lib", default-features = false, features = ["specs", "threaded", "crossterm"] }
specs_declaration = { path = "../specs_declaration" }
game_features = { path = "../game_features" }
specs = "0.16.1"
specs-derive = "0.4.1"
shrev = "1.1.1"
hibitset = "0.6.3"
derive-new = "0.5"
pushdown-automaton-macro = "0.1.0"

