[package]
name = "minigene"
version = "0.5.0"
authors = ["Joël Lupien (Jojolepro) <jojolepro@jojolepro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["terminal", "planck_ecs/parallel"]

# Rendering backends
# Currently, only one can be enabled at the same time
terminal = ["bracket-lib/crossterm", "crossterm"]
opengl = ["bracket-lib/opengl"]

# Enables WASM compatibility mode.
# Only works if using the opengl backend.
wasm = ["wasm-bindgen", "opengl", "web_worker"]

[dependencies]
bracket-lib = { git = "https://github.com/thebracket/bracket-lib", default-features = false, features = ["threaded", "serde"], rev = "d8c8af87173d0a26662fde108f7dc988ad3bed48" }

#game_features = { path = "../game_features" }
game_features = { version = "0.8.1" }

hibitset = "0.6.3"
derive-new = "0.5.8"
game_clock = { version = "1.0.0" }
stopwatch2 = "2.0.0"
spin_sleep = "1.0.0"
planck_ecs = { version = "1.2.0", features = ["big_systems"] }
rayon = { version = "1.4.0" }
oorandom = "11.1.3"
game_engine_core = "1.1.1"

crossterm = { version = "0.18.0", optional = true }

wasm-bindgen = { version = "0.2.68", optional = true }
web_worker = { version = "0.3.0", optional = true }
